import { Dispatch, SetStateAction } from "react";
import { FormData } from "@/types";

type Props = {
  nextStep: () => void;
  prevStep: () => void;
  formData: FormData;
  setFormData: Dispatch<SetStateAction<FormData>>;
};

export default function StepDisclaimer({
  nextStep,
  prevStep,
  formData,
  setFormData,
}: Props) {
  const handleCheckboxChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData((prev) => ({
      ...prev,
      agreedToTerms: e.target.checked,
    }));
  };

  return (
    <div>
      <h2 className="text-3xl font-bold text-gray-800 mb-6" style={{ fontFamily: "'Lora', serif" }}>
        Step 5: Legal Disclaimer & Agreement
      </h2>
      <div className="space-y-4 bg-amber-50 border-l-4 border-amber-400 p-6 rounded-md shadow-sm">
        <h3 className="text-lg font-bold text-amber-900" style={{ fontFamily: "'Lora', serif" }}>Please Read Carefully</h3>
        <div className="prose prose-sm max-w-none text-gray-800">
          <p>
            The policy templates generated by this website are for informational purposes only and do not constitute legal advice. They are provided as-is, without any warranty, express or implied.
          </p>
          <p>
            We are not a law firm and do not provide legal services. Your use of these templates does not create an attorney-client relationship.
          </p>
          <p>
            You are solely responsible for reviewing, editing, and ensuring that any policy generated meets the specific legal requirements of your business and jurisdiction. We strongly recommend that you consult with a qualified legal professional to review your generated policies before use.
          </p>
          <p>
            By checking the box below, you acknowledge and agree that we are not liable for any damages, losses, or causes of action of any nature arising from any use of the templates provided on this website.
          </p>
        </div>
      </div>
      <div className="mt-6">
         <label className="flex items-start p-4 border border-gray-200 rounded-lg hover:bg-gray-50 cursor-pointer">
            <input
              id="agree"
              name="agree"
              type="checkbox"
              checked={formData.agreedToTerms || false}
              onChange={handleCheckboxChange}
              className="focus:ring-slate-500 h-4 w-4 text-slate-600 border-gray-300 rounded mt-1"
            />
            <span className="ml-3 block text-sm font-medium text-gray-700">
             I have read, understood, and agree to the terms outlined in this disclaimer.
            </span>
          </label>
      </div>
      <div className="mt-8 flex justify-between items-center">
        <button
          onClick={prevStep}
          className="text-slate-600 font-bold py-3 px-6 rounded-lg hover:bg-slate-100 transition-colors"
        >
          Back
        </button>
        <button
          onClick={nextStep}
          disabled={!formData.agreedToTerms}
          className="bg-slate-800 text-white font-bold py-3 px-6 rounded-lg hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          Proceed to Final Review
        </button>
      </div>
    </div>
  );
} 