import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <main className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="bg-white rounded-lg shadow-md p-8">
        <div className="mb-8">
          <Link
            href="/"
            className="inline-flex items-center text-blue-600 hover:text-blue-800 mb-6"
          >
            <svg
              className="w-4 h-4 mr-2"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 19l-7-7 7-7"
              />
            </svg>
            Back to Policy Generator
          </Link>

          <h1
            className="text-4xl font-bold text-gray-900 mb-4"
            style={{ fontFamily: "'Lora', serif" }}
          >
            Legal Disclaimer
          </h1>

          <p className="text-lg text-gray-600 leading-relaxed">
            Important information about using the Policy Generator tool
          </p>
        </div>

        <div className="prose prose-lg max-w-none space-y-8">
          <section>
            <h2
              className="text-2xl font-bold text-gray-900 mb-4"
              style={{ fontFamily: "'Lora', serif" }}
            >
              ⚠️ This is Not Legal Advice
            </h2>
            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-6 mb-6">
              <p className="text-gray-800 font-medium">
                <strong>
                  The policies generated by this tool are for informational
                  purposes only and may not be suitable for your specific
                  circumstances.
                </strong>
              </p>
            </div>
            <p className="text-gray-700 leading-relaxed">
              The templates provided by this Policy Generator are not a
              substitute for legal advice from a qualified attorney. Laws vary
              by jurisdiction and change frequently. What works for one business
              may not work for another.
            </p>
          </section>

          <section>
            <h2
              className="text-2xl font-bold text-gray-900 mb-4"
              style={{ fontFamily: "'Lora', serif" }}
            >
              🔒 Use at Your Own Risk
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              The creators and contributors of this project are not liable for
              any errors or omissions in the generated documents, nor for any
              actions taken in reliance on the information provided.
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>
                We do not guarantee the accuracy, completeness, or reliability
                of the generated policies
              </li>
              <li>
                Legal requirements vary by country, state, and business type
              </li>
              <li>Policies may become outdated as laws change</li>
              <li>
                You are responsible for ensuring compliance with all applicable
                laws
              </li>
            </ul>
          </section>

          <section>
            <h2
              className="text-2xl font-bold text-gray-900 mb-4"
              style={{ fontFamily: "'Lora', serif" }}
            >
              👨‍⚖️ We Strongly Recommend Professional Review
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Before implementing any generated policies on your website or
              application, we strongly recommend that you:
            </p>
            <ol className="list-decimal list-inside text-gray-700 space-y-2 ml-4">
              <li>
                Consult with a qualified attorney who specializes in privacy
                law, terms of service, or the relevant legal area
              </li>
              <li>
                Have your policies reviewed for compliance with applicable laws
                in your jurisdiction
              </li>
              <li>
                Regularly update your policies as your business practices and
                applicable laws change
              </li>
              <li>
                Consider industry-specific requirements that may not be covered
                by our templates
              </li>
            </ol>
          </section>

          <section>
            <h2
              className="text-2xl font-bold text-gray-900 mb-4"
              style={{ fontFamily: "'Lora', serif" }}
            >
              🌍 Jurisdictional Considerations
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Legal requirements vary significantly across different countries,
              states, and regions. Our templates are based on common practices
              but may not address specific requirements in your jurisdiction,
              such as:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mt-4">
              <li>GDPR compliance for European users</li>
              <li>CCPA requirements for California residents</li>
              <li>Specific disclosure requirements in your country or state</li>
              <li>Industry-specific regulations (healthcare, finance, etc.)</li>
            </ul>
          </section>

          <section>
            <h2
              className="text-2xl font-bold text-gray-900 mb-4"
              style={{ fontFamily: "'Lora', serif" }}
            >
              📝 About This Tool
            </h2>
            <p className="text-gray-700 leading-relaxed">
              This Policy Generator is an open-source project created to help
              developers and small businesses get started with basic legal
              policies. It is provided as-is, without warranty of any kind. The
              tool is designed to save time and provide a starting point, but it
              should never replace professional legal advice.
            </p>
          </section>

          <section className="bg-blue-50 p-6 rounded-lg">
            <h2
              className="text-2xl font-bold text-gray-900 mb-4"
              style={{ fontFamily: "'Lora', serif" }}
            >
              💡 Our Recommendation
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Use this tool as a starting point to understand what policies you
              might need and what they typically contain. Then, work with a
              qualified attorney to ensure your final policies are appropriate,
              compliant, and tailored to your specific business needs.
            </p>
          </section>

          <div className="border-t pt-8 mt-8">
            <p className="text-sm text-gray-500 text-center">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
